### ISSUE TITLE
Styles: Status bar icon messes up other status bar items

### ISSUE THREAD

**Issue by r-murphy** [joeferraro/MavensMate-Atom#312]
The status bar icon is a bit too tall and causes standard status bar items to get pushes down so that they're only partially visible. The default display: inline contributes to the issue.

In the Atom Light theme, it's not too bad, although content still gets pushed down, but in Unity theme shown here, it's worse.

![image](https://cloud.githubusercontent.com/assets/658922/14985713/acec177c-1116-11e6-988d-b5943a686b3c.png)

Here is the fix I've applied to my Atom stylesheet. Note that I'm no css expert by any means.

```less
#mavensmateSvgIcon {
  display: block; //this gets it to vertically align center and avoids pushing other content down.
  height: 20px; //still enough clickable space
}
```

Which looks better:

![image](https://cloud.githubusercontent.com/assets/658922/14985843/38d09e48-1117-11e6-8b64-cfd0f97db2b0.png)
